# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-19 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receive',
            old_name='dev_id',
            new_name='devid',
        ),
        migrations.RenameField(
            model_name='receive',
            old_name='msg_id',
            new_name='msgid',
        ),
        migrations.AlterField(
            model_name='receive',
            name='data',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
