# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181220_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetogoods',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='devicetogoods',
            name='goods_id',
        ),
        migrations.AddField(
            model_name='device',
            name='goods',
            field=models.ManyToManyField(to='api.Goods'),
        ),
        migrations.DeleteModel(
            name='DeviceToGoods',
        ),
    ]
